use std::{io::ErrorKind, path::PathBuf};

use anyhow::{Result, anyhow};
use serde::Deserialize;

use crate::constants::LOCKFILE;

#[derive(Deserialize)]
pub(crate) struct Dep {
    pub(crate) name: String,
    pub(crate) source: String,
    pub(crate) commit: String,
}

#[derive(Deserialize)]
pub(crate) struct Lockfile {
    pub(crate) dep: Vec<Dep>, // Should Dep be private?
}

pub(crate) fn check_git() -> Result<()> {
    match std::process::Command::new("git").arg("--version").status() {
        Ok(_) => Ok(()),
        Err(_) => Err(anyhow!("git is not installed on your machine")),
    }
}

pub(crate) fn load_lockfile() -> Result<Lockfile> {
    match std::fs::read_to_string(PathBuf::from(LOCKFILE)) {
        Ok(res) => Ok(toml::from_str(&res)?),
        Err(e) => match e.kind() {
            ErrorKind::NotFound => Ok(Lockfile { dep: Vec::new() }), // Is the 'idiomatic' way `vec![]` or `Vec::new()`?
            _ => Err(anyhow!("{e}")),
        },
    }
}
// bank of unused code
// std::fs::write(
//     LOCKFILE,
//     "# This file is automatically generated by Odyn.\n# Do not edit this file manually unless you know what you're doing.",
// );
