use std::{io::ErrorKind, path::PathBuf};

use anyhow::{Result, anyhow};
use serde::{Deserialize, Serialize};

use crate::constants::LOCKFILE;

#[derive(Deserialize, Serialize)]
pub(crate) struct Dep {
    pub(crate) name: String,
    pub(crate) source: String,
    pub(crate) commit: String,
}

#[derive(Deserialize, Serialize)]
pub(crate) struct Lockfile {
    pub(crate) dep: Vec<Dep>,
}

pub(crate) fn check_git() -> Result<()> {
    match std::process::Command::new("git").arg("--version").output() {
        Ok(_) => Ok(()),
        Err(_) => Err(anyhow!("git is not installed on your machine")),
    }
}

pub(crate) fn load_lockfile() -> Result<Lockfile> {
    match std::fs::read_to_string(PathBuf::from(LOCKFILE)) {
        Ok(res) => Ok(toml::from_str(&res)?),
        Err(e) => match e.kind() {
            ErrorKind::NotFound => Ok(Lockfile { dep: Vec::new() }),
            _ => Err(anyhow!("{e}")),
        },
    }
}

pub(crate) fn save_lockfile(lockfile: &Lockfile) -> Result<()> {
    let header = "# This file is automatically @generated by Odyn.\n# Do not edit this file manually unless you know what you're doing.\n\n";
    let body = toml::to_string(lockfile)?;
    std::fs::write(LOCKFILE, format!("{header}{body}"))?;
    Ok(())
}

pub(crate) fn save_lockfile_at(lockfile: &Lockfile, path: &PathBuf) -> Result<()> {
    let header = "# This file is automatically @generated by Odyn.\n# Do not edit this file manually unless you know what you're doing.\n\n";
    let body = toml::to_string(lockfile)?;
    std::fs::write(path.join(LOCKFILE), format!("{header}{body}"))?;
    Ok(())
}

pub(crate) fn gen_main_odin(name: impl Into<String>) -> String {
    let name = name.into();
    format!(
        "package main

import \"core:fmt\"

main :: proc() {{
    fmt.println(\"Hellope, {name}!\")
}}"
    )
}

pub(crate) enum DepState {
    Ok,
    Missing,
    Modified { actual: String },
}
