use std::{
    io::ErrorKind,
    path::{Path, PathBuf},
};

use anyhow::{anyhow, Result};
use serde::{Deserialize, Serialize};

use crate::constants::LOCKFILE;

#[derive(Deserialize, Serialize)]
pub(crate) struct Dep {
    pub(crate) name: String,
    pub(crate) source: String,
    pub(crate) commit: String,
}

#[derive(Deserialize, Serialize)]
pub(crate) struct Lockfile {
    pub(crate) dep: Vec<Dep>,
}

pub(crate) fn check_git() -> Result<()> {
    match std::process::Command::new("git").arg("--version").output() {
        Ok(_) => Ok(()),
        Err(_) => Err(anyhow!("git is not installed on your machine")),
    }
}

pub(crate) fn load_lockfile() -> Result<Lockfile> {
    match std::fs::read_to_string(PathBuf::from(LOCKFILE)) {
        Ok(res) => Ok(toml::from_str(&res)?),
        Err(e) => match e.kind() {
            ErrorKind::NotFound => Ok(Lockfile { dep: Vec::new() }),
            _ => Err(anyhow!("{e}")),
        },
    }
}

pub(crate) fn save_lockfile(lockfile: &Lockfile) -> Result<()> {
    let header = "# This file is automatically @generated by Odyn.\n# Do not edit this file manually unless you know what you're doing.\n\n";
    let body = toml::to_string(lockfile)?;
    std::fs::write(LOCKFILE, format!("{header}{body}"))?;
    Ok(())
}

pub(crate) fn save_lockfile_at(lockfile: &Lockfile, path: &Path) -> Result<()> {
    let header = "# This file is automatically @generated by Odyn.\n# Do not edit this file manually unless you know what you're doing.\n\n";
    let body = toml::to_string(lockfile)?;
    std::fs::write(path.join(LOCKFILE), format!("{header}{body}"))?;
    Ok(())
}

pub(crate) fn gen_main_odin(name: impl Into<String>) -> String {
    let name = name.into();
    format!(
        "package main

import \"core:fmt\"

main :: proc() {{
    fmt.println(\"Hellope, {name}!\")
}}"
    )
}

pub(crate) enum DepState {
    Ok,
    Missing,
    Modified { actual: String },
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_lockfile_serialize() {
        let lockfile = Lockfile {
            dep: vec![Dep {
                name: "math".to_string(),
                source: "https://github.com/odin-community/math".to_string(),
                commit: "abc1234".to_string(),
            }],
        };
        let toml_str = toml::to_string(&lockfile).unwrap();
        assert!(toml_str.contains("name = \"math\""));
        assert!(toml_str.contains("source = \"https://github.com/odin-community/math\""));
        assert!(toml_str.contains("commit = \"abc1234\""));
    }

    #[test]
    fn test_lockfile_deserialize() {
        let toml_str = r#"
[[dep]]
name = "math"
source = "https://github.com/odin-community/math"
commit = "abc1234"
"#;
        let lockfile: Lockfile = toml::from_str(toml_str).unwrap();
        assert_eq!(lockfile.dep.len(), 1);
        assert_eq!(lockfile.dep[0].name, "math");
        assert_eq!(
            lockfile.dep[0].source,
            "https://github.com/odin-community/math"
        );
        assert_eq!(lockfile.dep[0].commit, "abc1234");
    }

    #[test]
    fn test_lockfile_empty() {
        let lockfile = Lockfile { dep: Vec::new() };
        let toml_str = toml::to_string(&lockfile).unwrap();
        assert!(toml_str.is_empty() || !toml_str.contains("[[dep]]"));
    }

    #[test]
    fn test_dep_state_variants() {
        let _ok = DepState::Ok;
        let _missing = DepState::Missing;
        let modified = DepState::Modified {
            actual: "abc1234".to_string(),
        };
        if let DepState::Modified { actual } = modified {
            assert_eq!(actual, "abc1234");
        }
    }
}
